src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity("slug")
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $article;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $date_added;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $date_updated;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank
     */
    private $slug;

    public function __toString(): string
    {
        return (string) $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getArticle(): ?string
    {
        return $this->article;
    }

    public function setArticle(string $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeImmutable
    {
        return $this->date_added;
    }

    public function setDateAdded(\DateTimeImmutable $date_added): self
    {
        $this->date_added = $date_added;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeImmutable
    {
        return $this->date_updated;
    }

    public function setDateUpdated(\DateTimeImmutable $date_updated): self
    {
        $this->date_updated = $date_updated;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setDateAddedValue()
    {
        $this->date_added = new \DateTimeImmutable();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function setDateUpdatedValue()
    {
        $this->date_updated = new \DateTimeImmutable();
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function computeSlug(SluggerInterface $slugger)
    {
        if (!$this->slug || '-' === $this->slug) {
            $this->slug = (string) $slugger->slug((string) $this)->lower();
        }
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Repository\NewsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Twig\Environment;

class NewsController extends AbstractController
{

    private $twig;
    private UrlGeneratorInterface $urlGenerator;

    public function __construct(Environment $twig, UrlGeneratorInterface $urlGenerator)
    {
        $this->twig = $twig;
        $this->urlGenerator = $urlGenerator;
    }

    /**
     * @Route("/", name="homepage")
     */
    public function index(): ?Response
    {

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $user = $this->getUser();
        $roles = $user->getRoles();
        if(in_array('ROLE_ADMIN', $roles)) {
            return $this->redirect($this->urlGenerator->generate('admin'));
        } elseif (in_array('ROLE_MODERATOR', $roles)) {
            return $this->redirect($this->urlGenerator->generate('news'));
        }
        return null;
    }

    /**
     * @Route("/news", name="news")
     */
    public function news(Request $request, NewsRepository $newsRepository): Response
    {
        $offset = max(0, $request->query->getInt('offset', 0));
        $paginator = $newsRepository->getNewsPaginator($offset);

        $user = $this->getUser();
        $roles = $user->getRoles();
        $is_admin = in_array('ROLE_ADMIN', $roles);
        return new Response($this->twig->render('news/index.html.twig', [
            'logged_in' => true,
            'is_admin' => $is_admin,
            'news' => $paginator,
            'previous' => $offset - NewsRepository::PAGINATOR_PER_PAGE,
            'current_page' => $offset / 10 + 1,
            'next' => min(count($paginator), $offset + NewsRepository::PAGINATOR_PER_PAGE),
        ]));
    }

    /**
     * @Route("/news/{id}", name="article")
     */
    public function show(News $article): Response
    {
        $user = $this->getUser();
        $roles = $user->getRoles();
        $is_admin = in_array('ROLE_ADMIN', $roles);
        return new Response($this->twig->render('news/show.html.twig', [
            'logged_in' => true,
            'is_admin' => $is_admin,
            'article' => $article,
        ]));
    }
}

templates/news/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}News{% endblock %}

{#{% block body %}#}
{#    <h2>View News Articles</h2>#}

{#    {% for article in news %}#}
{#        <h4>{{ article }}</h4>#}
{#        <p>#}
{#            <a href="{{ path('article', { id: article.id }) }}">View</a>#}
{#        </p>#}
{#    {% endfor %}#}
{#    <div>There are {{ news|length }} articles.</div>#}
{#    {% if previous >= 0 %}#}
{#        <a href="{{ path('homepage', { offset: previous }) }}">Previous</a>#}
{#    {% endif %}#}
{#    {% if next < news|length %}#}
{#        <a href="{{ path('homepage', { offset: next }) }}">Next</a>#}
{#    {% endif %}#}
{#{% endblock %}#}

{% block body %}
    <h2 class="mb-5">
        View News Articles
    </h2>

    {% for row in news|batch(2) %}
        <div class="row">
            {% for article in row %}
                <div class="col-12 col-md-6 col-lg-6 mb-4">
                    <div class="card border shadow lift">
                        <a href="{{ path('article', { id: article.id }) }}">
                            <div class="card-body">
                                <div class="card-title">
                                    <div class="mb-3"><img style="width: -webkit-fill-available" alt="Article picture" src="{{ article.picture }}" /></div>
                                    <h4 class="font-weight-light text-black">
                                        {{ article }}
                                    </h4>
                                </div>
                                <p class="text-black">
                                    {{ article.description }}
                                </p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if previous >= 0 %}
                <li class="page-item"><a class="page-link" href="{{ path('news', { offset: previous }) }}">Previous</a></li>
                <li class="page-item"><a class="page-link" href="{{ path('news', { offset: previous }) }}">{{ current_page - 1 }}</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ current_page }}</a></li>
            {% if next < news|length %}
                <li class="page-item"><a class="page-link" href="{{ path('news', { offset: next }) }}">{{ current_page + 1 }}</a></li>
                <li class="page-item"><a class="page-link" href="{{ path('news', { offset: next }) }}">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/news/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}News - {{ article }}{% endblock %}

{% block body %}
{#    <h2>{{ article }}</h2>#}

{#    <h4>{{ article.description }}</h4>#}
{#    <small>#}
{#        {{ article.dateAdded|format_datetime('medium', 'short') }}#}
{#    </small>#}

{#    {% if article.picture %}#}
{#        <img alt="Article picture" src="{{ article.picture }}" />#}
{#    {% endif %}#}

{#    <p>{{ article.article }}</p>#}

    <div class="row">
        <div class="col-12">
            <div class="media shadow border rounded-3 p-3 mb-4">
                <h4 class="font-weight-light text-black mb-3">
                    {{ article }}
                </h4>
                <div class="mb-3" style="text-align: center">
                    {% if article.picture %}
                        <a href="{{ article.picture }}" target="_blank">
                            <img src="{{ article.picture }}" alt="Article picture" />
                        </a>
                    {% endif %}
                </div>

                <div class="media-body">
                    <div class="mb-2">
                        <small class="text-muted text-uppercase">
                            {{ article.dateAdded|format_datetime('medium', 'short') }}
                        </small>
                    </div>

                    <p>
                        {{ article.article|nl2br }}
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}